### PR TITLE
Update to latest knative deps

### PR DESCRIPTION
**Pull request by rhuss**

### CODE REVIEW

**Comment by rhuss** [comment]
@dsimansk could I have a /lgtm please ?

**Comment by dsimansk** [comment]
I have a minor issue with the current impl of `hack/build.sh`. 

I'd suggest that the update_deps is changed to call `hack/update-deps.sh`, one of the benefits is clean up of OWNERS files from vendor dir, that are currently part of this PR.

https://github.com/knative-sandbox/kn-plugin-service-log/pull/22/files#diff-3d78da75ea6dd0aa86fac99d385c70af27002c3d2cc205934432150e2f2ccf9cL184-R188

More like client's script:
https://github.com/knative/client/blob/main/hack/build.sh#L185-L188

@rhuss anyway of course it can be addressed in the follow-up PR.

**Comment by rhuss** [comment]
@dsimansk thanks for the heads up, fixed the update call and some other things

**Review by dsimansk — COMMENTED** [review]
Thanks @rhuss, looks good to me now!

/approve
/lgtm

**Pull request merged**
